name: Precommit Community Metrics
run-name: Community Metrics Precommit
on:
  pull_request:
    branches: [ "*" ]
    #branches: [ "master", "release-*" ]
    #paths: [ ".test-infra/metrics/.*$"]
  issue_comment:
    types: [created, edited]
  workflow_dispatch:
   inputs:
     tags:
        description: 'Test scenario tags'
        required: false
        type: boolean


jobs:
  CommunityMetricsPrecommit:
#    if: ${{github.event.issue.pull_request}} || ${{github.event.comment.body == 'Run PythonDocker PreCommit'}} || ${{github.event.schedule == '* */6 * * *'}}
    runs-on: self-hosted


    steps:
      - uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3.8.0
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
      - name: run Community Metrics Precommit script
        run: gradlew :communityMetricsPreCommit
