name: Precommit Python 
run-name: Python Precommit
on:
  pull_request:
    branches: [ "*" ]
  issue_comment:
    types: [created, edited]
  workflow_dispatch:
   inputs:
     tags:
        description: 'Test scenario tags'
        required: false
        type: boolean


jobs:
  PythonPrecommit:
#    if: github.event.workflow_dispatch || (github.event.issue.pull_request && contains(github.event.comment.body, 'Run PythonLint PreCommit'))
    runs-on: self-hosted
    defaults:
      run:
        working-directory: sdks/python


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7 - 3.11'
      - name: Install Dependencies
        run:  pip install --retries 10 --upgrade pip && ls && pwd && pip install --retries 10 --upgrade tox==3.20.1 -r ./build-requirements.txt
        working-directory: sdks/python
      #- name: Run python cloud 
        #run: tox -s "true" run py37-cloud
        #working-directory: sdks/python
      - name: Run cython
        run: tox -e py38-cython -- --ignore=apache_beam/dataframe/ --ignore=apache_beam/examples/ --ignore=apache_beam/runners/ --ignore=apache_beam/transforms/
        working-directory: sdks/python
