name: Precommit Community Metrics

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
   inputs:
     tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

env:
  cluster: metrics
  zone: us-central1-a
  projectName: ${{env.gcloud_ProjectName}}
  kubeConfigPath: ./beam/jenkins/.kube/config

jobs:
  Composer:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'Run CommunityMetrics PreCommit')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Change working directory
        run: cd .test-infra/metrics
      - name: compose-build
        run: docker-compose build
  Validate_Configuration:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'Run CommunityMetrics PreCommit')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Cluster Credentials
        run: gcloud container clusters get-credentials $cluster --zone $zone --project $projectName
      - name: Validate K8s Configuration
        uses: ghostzero/kubectl@v1
        with:
          args: apply --dry-run=client -Rf kubernetes

      #- name: Test Metrics Stack
        #run: TODO(BEAM-5837): Add some actual validation of the metrics stack

      - name: Remove Kube Config
        run: rm $kubeConfigPath

