name: Precommit Python Lint
run-name: Python Lint
on:
  pull_request:
    branches: [ "*" ]
  issue_comment:
    types: [created, edited]
  workflow_dispatch:
   inputs:
     tags:
        description: 'Test scenario tags'
        required: false
        type: boolean


jobs:
  PythonLint:
#    if: github.event.workflow_dispatch || (github.event.issue.pull_request && contains(github.event.comment.body, 'Run PythonLint PreCommit'))
    runs-on: self-hosted
    #defaults:
      #run:
        #working-directory: sdks/python


    steps:
      - uses: actions/checkout@v3
      - name: Install python versions
        run: apt install -y 
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7 - 3.11'
      - name: Install Dependencies
        run:  pip install --retries 10 --upgrade pip && ls && pwd && pip install --retries 10 --upgrade tox==3.20.1 -r ./build-requirements.txt
        working-directory: sdks/python
      - name: Copy licenses
        run: mkdir -p build/target && cp LICENSE LICENSE.python NOTICE build/target
      - name: Go Build
        run: go1.20.4 build -o ./build/target/launcher/linux_amd64/boot *go
        working-directory: sdks/python
